### ISSUE TITLE
Rendering Time

### ISSUE THREAD

**Issue by 2xSamurai** [obogo/ux-angularjs-datagrid#109]
First of all, I really like what you have done here. 

I tried implementing your plugin in ionic v1(on angularjs). But I came across a problem which I couldn't solve. The problem is, I have a large list ( around 1000 items ). When rendering for the first time ( initial view load ), the items are loaded very slowly. That is, while this initial load is happening if scrolled down, we can see a lot of empty spaces. I'm not sure how to solve this.

I am pasting my code also, in case if you need to take a look at it. I'm not sure what I am doing wrong. Spent a day trying to figure this out. Sorry to cause you trouble.
**P.S:** I have seen that your plugin can do up to 7k rows easily. So I guess its something wrong at my side.

`<div ux-datagrid="items">`
    `<script type="template/html" template-item="item">`
        `<div class="ex1-row"><span>{{$index}}</span></div>`
    `</script>`
`</div>`

I tried a complex template first, then I tried the above code as well. But it did not help.

Also one more question. Can I use like {{item.id}} inside the template (to access keys inside my object array)? Or is there any specific way to do this.

I am using **-webkit-overflow-scrolling: touch;**. will it cause any issue. I am testing on an iPhone 6S

**Comment by wesjones** [comment]
The styles of the datagrid need to be set so it causes the overflow scrolling on the grid element. If the height isn't set so it causes overflow scrolling on the grid then it will try to render all at once and be very slow.

If you set the height of the grid with something like this then it gives a fixed height in which to render.
div[ux-datagrid] { position: absolute; top: 40px; bottom: 0px; }

With rows as simple as what you are doing it should render those rows pretty quickly. Yes you should be able to scroll down to get ahead of it, but only if you are really trying. The grid renders asynchronously in the background but it doesn't render everything. It renders only so far in each direction. You can change how much is rendered to improve performance or distance of what is there. 
You will find these settings in the options. You can change them after the angular-ux-datagrid.js has loaded by accessing them globally `ux.datagrid.options.renderThreshold=4;`. Or you can set them for each individual grid by setting the options for that grid in the html of it. [Using Options](http://obogo.github.io/ux-angularjs-datagrid/#usingOptions).

To see what options are available. Look into the angular-ux-datagrid script for options this way you will be able to see the comments related to each option. Options start around line 618.

**Comment by 2xSamurai** [comment]
Thank you, Wes. I understand. I saw the options. Thanks for your help.
