### ISSUE TITLE
Datagrid not destroying row scopes when grid is child of isolate scope (component).

### ISSUE THREAD

**Issue by ryancanulla** [obogo/ux-angularjs-datagrid#111]
The issue seems to be that when we do use an isolate scope the $$destroyed property is not set on the new scope so it goes up the prototype chain to the highest level of the isolate scope to get this property. Since at this point the parent is already destroyed, it's skipping the destroy on all of the row scopes as it thinks they are already destroyed. 

This seems to fix the issue but I wanted to check with you guys to see if there is a better way and/or something that we haven't thought of. 

`function compileRow(index, el) {
        var s = scopes[index], currentRow;
        if (s && !s.$parent) {
            s.$parent = scope;
        }
        if (!s) {
            // fixes a bug expanding the last row and trying to scroll to it.
            if (!scope.$$childTail && scope.$$childHead && scopes[index - 1]) {
                scope.$$childTail = scopes[index - 1];
            }

            s = scope.$new();

            // if the parent scope is isolate then the new scope will use prototypial inheritence
            // to get this property during the destroy phase. the issue is at the point of destruction
            // the parent scope has already been destroyed so it will bypass the destroy phase for this scope.
            // setting it to false will ensure that it does not go up the prototype chain and properly maintains the state
            // whether it has been destroyed.
            s.$$destroyed = false;

            //s.$on('$destroy', function() {
            //   console.log('DESTROY ' + s.$id + ' index:' + s.$index);
            //});
            processCompilation(s, index, el);
        } else if (s && (currentRow = getExistingRow(index)).scope() !== s) {
            // after rows are destroyed (memory optimizer) then they need to be recompiled.
            processCompilation(s, index, currentRow);
        }
        return s;
    }`

**Comment by wesjones** [comment]
I like your solution. I think it works well. I was worried about it causing an infinite loop but I don't think so because it will now have the false set locally to just that scope and should set the true there as well. I think it is a very good solution.

**Comment by wesjones** [comment]
Thanks for the catch Ryan. Great to hear from you again. 👍 It is published as 1.6.13.

**Comment by ryancanulla** [comment]
Sweet! Shoot me a note at my first and last name at gmail so I can get your latest email address! I wanna catch up and see how everything is going! The one on your github account is bouncing back.

**Comment by wesjones** [comment]
Thanks, yes I forgot to update that email. :) talk to you soon.
