### ISSUE TITLE
Doc Request: nested items

### ISSUE THREAD

**Issue by Joebob12** [obogo/ux-angularjs-datagrid#64]
Hello great directive here. I got it working excellent with one template but ran into an issue trying to replace my inner ng-repeat with another template. Kind of like grouped data. more like nested data.

so let me simplify my html here:
```
  <div data-ng-controller="index.dataGridController" data-ux-datagrid="index.items" class="listA datagrid" data-addons="whichTemplate"  grouped="'focus'">
      <script type="template/html" data-template-name="default" data-template-item="item">
        <div>
            <h3>{{ item.obj.name }}</h3>
             <!--- instead of 
             <ul>
                 <li ng-repeat="listItem in item.focus>{{listitem}}</li>
              </uL
              -->
        </div>
      </script>
      <script type="template/html" data-template-name="innerFocus" data-template-item="item">
        <div>
          <ul>
            <li>{{item.focus.id}}</li>
          </ul>
        </div>
      </script>
  </div>
```
and the index.items look like this:
```
[{
    "obj": {
    "name": "someName" 
    }
    "focus": [
    {"id": "something here"},
    {"id": "Another etc"}
    ]
}]
```

```
// which template is basically copy and pasted from examples
angular.module('ux').factory('whichTemplate', function () {
     return function (inst) {
        // now we override it with our method so we decide what template gets displayed for each row.
        inst.templateModel.getTemplate = function (item) {
            var name = item.focus ? 'innerFocus' : 'default';
            // now we get the template from the name.
            return inst.templateModel.getTemplateByName(name);
        };
    };
});
```
Trying to iterate a list with the focus array. Any ideas? I think it would make for a great example in the docs. Adding a fiddle. http://jsfiddle.net/uftsG/88/
Instead of putting all focus array in one li i'm trying to get them spread out while also having the item.obj.name above the list.

**Comment by wesjones** [comment]
Sorry it has taken me so long to respond. I saw this email and thought I would answer it later at the time and forgot. So sorry.

After looking at your example I fixed up the fiddle to work. 

http://jsfiddle.net/waq67ne0/

It appears that you were setting the wrong template here. You were setting the child input for the group input. And you want to make sure you double nest your inputs (<div><span>stuff</span><div> instead of <div>stuff</div>) for the styles to work so it doesn't show uncompiled elements until they are compiled.

```javascript
var name = item.focus ? 'innerFocus' : 'default';
```

It should be .

```javascript
var name = item.focus ? 'default' : 'innerFocus';
```
