### ISSUE TITLE
How to use SwapItem & Resize for columns

### ISSUE THREAD

**Issue by pooja-avantsoft** [obogo/ux-angularjs-datagrid#65]
Hi,

   I am new to this ux-datagrid so I would like to integrate functionality for swapping(drag/drop) of columns and I should be able to resize columns size.

I have seen the documentation but not getting how to implement/take in use in my html template

Thanks,
Any kind of help will be appreciated

**Comment by wesjones** [comment]
Drag resize columns sounds reasonable. I can put together an example for that. However, for dragging and dropping columns that may get more complicated. You are welcome to write an addon for that if you like. Please check out the other addons for examples of how to do so. I'll get back to you on dragging the columns to resize them.

**Comment by pooja-avantsoft** [comment]
Thanks a lot it would be very helpful for me. Possibly once I get idea about resizing then might be I can write addon for drag-drop of column

**Comment by pooja-avantsoft** [comment]
Is this enhancement done... ??

**Comment by wesjones** [comment]
Nope Sorry, still working on it.

**Comment by wesjones** [comment]
Ok, it is ready. This is not a datagrid addon because the datagrid has nothing to do with headers. So this is a directive that just manipulates the styles of the datagrid to resize the columns.

http://obogo.github.io/ux-angularjs-datagrid/#/resizeColumns
