### ISSUE TITLE
Horizontal grid

### ISSUE THREAD

**Issue by AlexParamonov** [obogo/ux-angularjs-datagrid#67]
How to create a horizontal grid? 
ux-datagrid adds inline style for the height, but seem have no configuration to be used as horizontal scrolling grid.

**Comment by wesjones** [comment]
Correct. Horizontal grid scrolling is not implemented.

**Comment by AlexParamonov** [comment]
But that does not stop people to use it :) 
I was forced to use some !important styles, but your grid boosted a performance a lot.
Using it in horizontal version. A bit hacky, but it worse it. Thank you :+1:

**Comment by wesjones** [comment]
Awesome! Glad to hear it. Thanks!
