### ISSUE TITLE
'whichTemplate' factory example is not compatible with strict dependency injection

### ISSUE THREAD

**Issue by etripier** [obogo/ux-angularjs-datagrid#71]
Hi Obogo,

On your website and in your readme, you have an example of a custom addon named 'whichTemplate', defined below:

```javascript
angular.module('ux').factory('whichTemplate', function () {
    return function (inst) {
        // now we override it with our method so we decide what template gets displayed for each row.
        inst.templateModel.getTemplate = function (item) {
            // item would be the item in your array of data provided to the datagrid.
            // let's make our default option be 'row'. Otherwise datagrid defaults this to 'default'.
            var name = item.type || 'row';
            // now we get the template from the name.
            return inst.templateModel.getTemplateByName(name);
        };
    };
});
```

Unfortunately this seems to throw an error in more recent versions of Angular with strict dependency injection enabled. I've fixed the error on my end by wrapping the `return` statement like so:

```javascript
return ['inst', function (inst) {
  inst.templateModel.getTemplate = function (item) {
    var name = item.searchChildren ? 'group' : 'row';
    return inst.templateModel.getTemplateByName(name);
  };
}];
```

Not a big deal but you've followed this convention in all the addons you developed for ux-datagrid, so the examples should be consistent to avoid issues.

Thanks for ux-datagrid by the way! It's great.

**Comment by wesjones** [comment]
Thanks for catching that and letting me know.
 I updated the examples.
http://obogo.github.io/ux-angularjs-datagrid/
