### ISSUE TITLE
 expandAll and CollapseAll on event click.

### ISSUE THREAD

**Issue by narendrapatilg** [obogo/ux-angularjs-datagrid#72]
I am Using the ExapandableGroups. 
In that I want to do a event call on which all groups will exanded/ collapse. 
How can I call  expandAll and CollapseAll.

**Comment by wesjones** [comment]
I'm not sure if I understand your question correction. Are you wanting to tell it to expand based on an event? If so these are the events you use.

```
ux.datagrid.events.COLLAPSE_ALL_GROUPS;
ux.datagrid.events.EXPAND_ALL_GROUPS;
ux.datagrid.events.COLLAPSE_GROUP;
ux.datagrid.events.EXPAND_GROUP;
ux.datagrid.events.TOGGLE_GROUP;
```

Otherwise if you want to get which groups are expanded you can loop through the data and get only the open groups.

```
var data = scope.datagrid.getData();// This is normalized data. So it will be items and groups together in one array of only the ones that are open. In this plugin, it does not show in the data if it is collapsed.
var openGroups = [];
for(var i = 0, len = data.length; i < len; i += 1) {
   if (scope.datagrid.expandableGroups.isGroup(data[i])) {
      openGroups.push(data[i]);
   }
}
```

**Comment by narendrapatilg** [comment]
thanks for your solution. 
can you provide the simple example for particular ExpandALl and CollapseAll event

**Comment by wesjones** [comment]
Yeah, you are right. That didn't work. Here is an example that actually does ;).

http://localhost:63342/ux-datagrid-io/index.html#/expandableGroups

I added to the expandableGroups example a count of items. It is generated from lists generated of the groups.

```
            $scope.expanded = 0;
            $scope.collapsed = items.length;
            function getCounts() {
                var grid = ux.datagrid.getGrid($scope);
                var groupedAndCollapsed = grid.expandableGroups.getItems();
                $scope.expanded = groupedAndCollapsed.expanded.length;
                $scope.collapsed = groupedAndCollapsed.collapsed.length;
            }
            $scope.$on(ux.datagrid.events.EXPAND_GROUP_CHANGE, getCounts);
```
