### ISSUE TITLE
Grid slower than ngrepeat

### ISSUE THREAD

**Issue by dvrakas** [obogo/ux-angularjs-datagrid#73]
It is still slow with 12 items in a template, am I missing something.  All that is different form the samples is that I'm displaying more items than just a integer value. 12 to be exact.

**Comment by wesjones** [comment]
Can you provide a JS Fiddle or something that can be looked at. There is little I can understand from your comment above.

A template is usually for a row. Not to have 12 items in one template. It should be one or more templates and 12 items which use that on template.

**Comment by dvrakas** [comment]
thank you for the response. I have one template being repeated. In that single template I have 12 items being displayed. Just like the example you have provided has one item in the template.  All I did is take the example and added 11 more scope vars.. Eg Name, address, phone, rating, etc. I think the my rate directive may be causing the slowness.

**Comment by wesjones** [comment]
I'm not sure which directive is the "MyRate" directive? Can you provide a link to the example you are using?

**Comment by dvrakas** [comment]
Its the ui bootstrap rate directive. When removed it seems to work fine.

**Comment by wesjones** [comment]
Sounds good. thx
