### ISSUE TITLE
Suggestion to use ng-cloak instead of CSS transition to hide rows that have not been loaded

### ISSUE THREAD

**Issue by etripier** [obogo/ux-angularjs-datagrid#79]
You recommend the following CSS to avoid users seeing Angular placeholders before data is fully loaded into the $scope:

```
.datagrid-row > * {
   -webkit-transition: opacity 0.5s ease-out;
   -moz-transition: opacity 0.5s ease-out;
   -ms-transition: opacity 0.5s ease-out;
   -o-transition: opacity 0.5s ease-out;
   transition: opacity 0.5s ease-out;
}

.uncompiled > * {
   visibility: hidden;
   opacity: 0;
}

.compiled > * {
   opacity: 1;
}
```

Rather than doing this, which produces a noticeable delay when scrolling before rows are visible, and having to guess at a transition duration that completely masks stuff like {{ dataExample }}, why not use ng-cloak on every row with Angular markup? I have been doing the following in my projects using ux-datagrid:

```
<div ux-datagrid="items">
    <script type="template/html" data-template-name="default" data-template-item="item">
        <div ng-cloak class="row">{{item}}</div>
    </script>
</div>
```

This could be a suggested improvement or option in your documentation, or, alternatively, you could have some sort of option to add the ng-cloak attribute to every row. Just a thought!

**Comment by etripier** [comment]
Actually, because `ng-cloak` applies a `display: none` CSS property, the HTML would look something like this:

```
<div class="row">
    <span ng-cloak>{{item}}</span>
</div>
```

**Comment by wesjones** [comment]
I don't think the first example wouldn't work because the row wouldn't hold its dimensions and throw off the layout of items in the grid.

I think the second example might. Have you tried it?
If you take out all of the css you have listed above and you should be able to see if it works.

**Comment by etripier** [comment]
I'm using the method described in my second example and it works like a charm (after removing your example CSS). As long as you have a `div` with a defined height, you can put a `span` or `div` inside it with an `ng-cloak` attribute and your Angular placeholder and the row will pop into view in significantly less than 0.5s.

I think it would be worth mentioning in your documentation - if you'd like, I can write something up on it. It could be useful for someone seeking aggressive optimizations to loading rows.

**Comment by wesjones** [comment]
I do like the example. I'll try to put an example into the docs with it. It would simplify setup, not needing that extra css. I'll try to comment here when I have the example updated.

**Comment by wesjones** [comment]
ng-cloak example now provided.
http://obogo.github.io/ux-angularjs-datagrid/
