### ISSUE TITLE
safeDigest() not actually safe

### ISSUE THREAD

**Issue by maximumduncan** [obogo/ux-angularjs-datagrid#87]
`safeDigest()` uses `isDigesting()` to check whether a Angular digest is already in progress before calling `$digest()`. Unfortunately it only checks the child scope's $$phase, not the root scope's $$phase:

    function isDigesting(s) {
        return !!(s && s.$$phase);
    }

Given that within Angular, the $$phase property is only checked on the root scope (in Angular's ``beginPhase()`` method) before allowing a digest, surely `isDigesting()` should be updated to check the same thing?

For example:

    function isDigesting(s) {
        return !!(s && s.$root.$$phase);
    }

For reference I'm getting "$digest already in progress" when trying to use version 1.4.8 of ux-datagrid.

**Comment by wesjones** [comment]
I believe the property is inherited through the prototype so you only have to check it on the scope you are in. Check out this example where I have copied out only small pieces of the scope from angularjs-1.4.3.js.

It creates a rootScope and then uses the exposed $new on the scope to create a child scope. After that is done, we then set a property on the $rootScope and you can read it from the child scope.
https://jsfiddle.net/wesjones/cphecumw/

So this example should illustrate that we wouldn't need to check the value on the $rootScope.

However, this doesn't solve the problem that you are getting. So we may want to try a couple of experiments. Try replacing your isDigesting function with this one below in your datagrid to see if it solves the problem. Please let me know.

```

function isDigesting(s) {
        var ds = s;
        while (ds) {
            if (ds.$$phase) {
                return true;
            }
            ds = ds.$parent;
        }
        return false;
}

```

**Comment by maximumduncan** [comment]
Okay if I replace the `isDigesting()` method with your supplied implementation I no-longer experience the issue.

If I break in the debugger on the `return true;` line, the following output can be obtained from the console:

    s.$$phase
    null
    s.$parent.$$phase
    null
    s.$parent.$parent.$$phase
    null
    s.$parent.$parent.$parent.$$phase
    "$digest"
    s.$root.$$phase
    "$digest"

Let me know if you'd like me to gather more information.

**Comment by maximumduncan** [comment]
After a little more digging it seems that `$$phase` goes to null on inherited scopes as soon as it goes into a directive using isolate scope; in my case this is a directive which I have wrapping your ux-datagrid.

Looking at the Angular source, when a scope is "newed" up by calling `scope.$new()`, if `isolate` is set then the child scope *doesn't* inherit from the parent via prototype (normally this happens in the `createChildScopeClass()` method which isn't called for isolate scopes). Only a few properties, such as the `$root` property, are copied over and apart from those it's a completely detached instance. I think this explains what we're seeing?

**Comment by wesjones** [comment]
Awesome! Thanks for your research on this. I have one last test. Because I want to avoid the lookup loop just for performance.

```

function isDigesting() {
   return return !!(s && s.$$phase || s.$root.$$phase);
}

```

Can you please let me know how this one works? It should be faster than the loop but still accomplish the same thing.

**Comment by maximumduncan** [comment]
I replaced it with the following (minor edits on your example):

    function isDigesting(s) {
        return !!(s && s.$$phase || s.$root.$$phase);
    }

And it works as expected :+1:

**Comment by wesjones** [comment]
Great! Thanks for testing that. I have the new release ready to go. 1.4.9

**Comment by maximumduncan** [comment]
New release fixes the issue. Thanks for your help.

**Comment by wesjones** [comment]
Your welcome. Thank you as well.
