### ISSUE TITLE
Angular module var hides potential ambient module instance when included by module loader

### ISSUE THREAD

**Issue by duncangrist** [obogo/ux-angularjs-datagrid#88]
At the top of `angular-ux-datagrid.js` there is a UMD definition which can depend upon the potential existence of an ambient symbol `module`.

Unfortunately, around line 437, `module` is redeclared (to reference the Angular module) which hides the ambient definition of `module` if it was available (i.e. if it was supplied by webpack or other module loader).  This causes the `module` symbol inside the UMD callback to be read back as `undefined`, breaking the module loader.

Could we change `var module` to `var ngModule` or otherwise pull the UMD definition into a scope which would be unaffected by `var module` ?

**Comment by wesjones** [comment]
That is a good catch. Thanks it has been updated in v1.4.11. Please update using. (npm and bower updates are available)
