### ISSUE TITLE
"ux" variable not available when loaded as part of a package

### ISSUE THREAD

**Issue by duncangrist** [obogo/ux-angularjs-datagrid#89]
Me again!

Continuing my integration of webpack into my project (thanks for your previous fix btw) I've noticed some other inconsistencies in the datagrid code.

For example, consider the following block:

    inst.unwatchers.push(inst.scope.$on(exports.datagrid.events.ON_AFTER_HEIGHTS_UPDATED, onAfterHeightsUpdated));
    inst.unwatchers.push(inst.scope.$on(exports.datagrid.events.ON_BEFORE_RESET, onBeforeReset));
    inst.unwatchers.push(inst.scope.$on(exports.datagrid.events.ON_AFTER_RESET, onAfterReset));
    inst.unwatchers.push(inst.scope.$on(ux.datagrid.events.ON_RENDER_AFTER_DATA_CHANGE, result.calculateBottomOffset));

You'll note that the bottom line tries to use the global `ux` instance, which isn't actually defined for me when I load `angular-ux-datagrid` using webpack. `exports.datagrid` *is* defined and hence I was wondering why the discrepancy?

I've simply hacked the line above to look like the ones above it and also changed this block:

    result.checkForEnds = function() {
        if (inst.values.scroll && inst.values.scroll >= bottomOffset) {
            inst.dispatch(ux.datagrid.events.ON_SCROLL_TO_BOTTOM, inst.values.speed);
        } else if (inst.values.scroll <= 0) {
            inst.dispatch(ux.datagrid.events.ON_SCROLL_TO_TOP, inst.values.speed);
        }
    };

to this:

    result.checkForEnds = function() {
        if (inst.values.scroll && inst.values.scroll >= bottomOffset) {
            inst.dispatch(exports.datagrid.events.ON_SCROLL_TO_BOTTOM, inst.values.speed);
        } else if (inst.values.scroll <= 0) {
            inst.dispatch(exports.datagrid.events.ON_SCROLL_TO_TOP, inst.values.speed);
        }
    };

And my app is running okay now. I've noticed there are a couple of other root `ux.` references in the code; they're probably not erroring for me as I'm not invoking their functionality but I'd imagine they'd want to be changed too.

**Comment by wesjones** [comment]
Thanks @duncangrist, your help in cleaning up the code has been much appreciated! It has been committed in v1.4.12

**Comment by duncangrist** [comment]
No worries :) Did you push the latest version to npm? npm is still listing 1.4.11 as the latest...

**Comment by wesjones** [comment]
Oops! It is pushed now thanks :)
