### ISSUE TITLE
windowScroll - eventlistener is not removed

### ISSUE THREAD

**Issue by m4r71n** [obogo/ux-angularjs-datagrid#93]
Hi @wesjones,

I'm using the windowScroll addon and get errors after a route change because the datagrid is destroyed but the scroll eventlistener on `window` will be still triggered.
I've temporarily fixed this by adding
```
if (angular.element(document).injector().get('windowScroll')) {
    window.removeEventListener("scroll", inst.scrollModel.onUpdateScroll)
}
```
to the `destroy()` method.
This seems a bit ugly so no PR but if you provide me with a hint how to do it better I'll try to send a PR.

Btw. thank you very much for this awesome datagrid!

**Comment by wesjones** [comment]
Thanks :) I'm not sure how I missed that one! And I am glad you are enjoying the datagrid.
This is fixed and added to release 1.5.3.
