### ISSUE TITLE
Infinite scroll trigger prematurely

### ISSUE THREAD

**Issue by robhicks** [obogo/ux-angularjs-datagrid#97]
I am using the datagrid with infinite scroll in an Angular 1.5 SPA in a couple of places. The app uses the Angular 1.5 component router. Views containing the datagrid are activated when the user browses to the route for the view. Of course a user can land on a view with the datagrid by entering the route in the browser, or more likely bookmarking the view.

When the view is loaded directly (rather than browsing to it from another view of the SPA), the datagrid code logs two warnings, 'Datagrid cannot have height of 0' and 'Template height change from 0 to 58. This can cause gaps in the datagrid.'

Then the datgrid triggers the ON_SCROLL_TO_BOTTOM too early. I assume it does it because it has calculated that each row has no height. This of course, loads data into the grid placing additional rows basically on top of each other. 

The container of the data grid is absolutely position using css to take up the entire height of the view. Each row of the datagrid is also given a fixed height.

When the view is not loaded directly, but browsed to from the menu of the app, the infinite scrolling of the grid works as expected.

Any ideas what might be happening and how to correct it?

**Comment by wesjones** [comment]
For the datagrid to work, your rows must have an explicit css height on the rows. It doesn't support dynamic rows because it uses many calculations to anticipate heights.

Once you have a fixed height on your rows, you should not have this issue.

```

   .datagrid-row {
      height: 40px;
   }

```
